modLoader="javafml"
loaderVersion="[47,)"
license="CC0-1.0"
issueTrackerURL="https://github.com/tzwgoo/yokonex-link/issues"

[[mods]]
modId="yokonex_link"
version="1.0.0"
displayName="YOKONEX-Link"
logoFile="icon.png"
credits="辞年"
authors="辞年"
description='''
YOKONEX-Link - 役次元硬件连接模组
通过WebSocket连接役次元硬件设备，将真实世界的动作同步到Minecraft游戏中。
支持多种游戏事件的实时监听和反馈。
'''
displayURL="https://www.github.com/tzwgoo"

[[mixins]]
config="yokonex-link.mixins.json"

[[dependencies.yokonex_link]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.yokonex_link]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
